#https://docs.skriptlang.org/classes.html

	
options:
    rewardReq: 3, 5, 8, 10, 13, 15, 18, 20, 25, 30, 35, 40, 45 and 50
    rewards: 64 experience bottle, 64 sunflower named "<reset><yellow>&lCoin", 128 experience bottle, 6 netherite ingot, 1 paper named "<reset><red>&lKillstreak Voucher", (1 of unbreakable diamond coast golden helmet of protection 9, unbreaking 255 and mending) named "<yellow><bold>CROWN", 4 paper named "<reset><red>&lKillstreak Voucher", 6 paper named "<reset><red>&lKillstreak Voucher", 7 paper named "<reset><red>&lKillstreak Voucher", 8 paper named "<reset><red>&lKillstreak Voucher", 9 paper named "<reset><red>&lKillstreak Voucher", 10 paper named "<reset><red>&lKillstreak Voucher", 10 paper named "<reset><red>&lKillstreak Voucher" and 15 paper named "<reset><red>&lKillstreak Voucher"
    bounty: 32 sunflower named "<reset><yellow>&lCoin", 48 sunflower named "<reset><yellow>&lCoin", 64 sunflower named "<reset><yellow>&lCoin", 1 paper named "<reset><red>&lKillstreak Voucher", 2 paper named "<reset><red>&lKillstreak Voucher", 4 paper named "<reset><red>&lKillstreak Voucher", 5 paper named "<reset><red>&lKillstreak Voucher", 6 paper named "<reset><red>&lKillstreak Voucher", 7 paper named "<reset><red>&lKillstreak Voucher", 8 paper named "<reset><red>&lKillstreak Voucher", 9 paper named "<reset><red>&lKillstreak Voucher", 10 paper named "<reset><red>&lKillstreak Voucher", 11 paper named "<reset><red>&lKillstreak Voucher" and 20 paper named "<reset><red>&lKillstreak Voucher"
function checkKS(p: player):
    set {_uuid} to {_p}'s uuid
    set {_rewardReq::*} to {@rewardReq}
    set {_rewards::*} to {@rewards}
    set {_bounty::*} to {@bounty}
    if {killStreak::%{_uuid}%} is 20:
        broadcast "<red><bold>%{_p}% IS ON FIRE! THEY'VE REACHED A TWENTY KILLSTREAK!!!"
        broadcast "%{_p}% has been awarded with <green><bold>%{_rewards::8}%"
        set {playerBounty::%{_uuid}%} to {_bounty::8}
        broadcast "<green><bold>LET THE HUNT BEGIN! %{_p}%'s BOUNTY HAS BEEN RAISED TO <reset><red><bold>%{_bounty::8}%!! THEY NOW EXUDE A MURDEROUS AURA!"
        #{_rewards::%loop-index%} is a number:
        #add {_rewards::%loop-index%} to {_p}'s balance
        give {_rewards::8} to {_p}
        set {godmode::%{_uuid}%} to true
        while {godmode::%{_uuid}%} is true:
            apply swiftness 2 to {_p}
            apply glowing to {_p}
            apply strength 2 to {_p}
            wait 100 ticks
    else:
        loop {_rewardReq::*}:
            if {killStreak::%{_uuid}%} is loop-value:
                broadcast "<red><bold>%{_p}% had reached a killstreak of %{killStreak::%{_uuid}%}%!"
                broadcast "%{_p}% has been awarded with <green><bold>%{_rewards::%loop-index%}%"
                set {playerBounty::%{_uuid}%} to {_bounty::%loop-index%}
                broadcast "%{_p}%'s bounty has increased to <red><bold>%{_bounty::%loop-index%}%!"
                #{_rewards::%loop-index%} is a number:
                    #add {_rewards::%loop-index%} to {_p}'s balance
                give {_rewards::%loop-index%} to {_p}
                stop

#on death of player:
    #clear {killStreak::%victim's uuid%}
    #if attacker is a player:
        #add 1 to {killStreak::%attacker's uuid%}
    #checkKS(attacker)


on death of player:

    #broadcast "event-damagecause is <bold>%event-damagecause%"

    set {_drops::*} to drops  
    clear drops
    loop {_drops::*}:
        drop loop-value at victim
        set velocity of last dropped item to vector(random number between 0 and 0.1, 0.1, random number between 0 and 0.1)
    clear {specialkitlist::%victim's uuid%}
    clear {godmode::%victim's uuid%}    
    #if {playerBounty::%victim's uuid%} is set:
        #give {playerBounty::%victim's uuid%} to {_playerWhoDetonated}
        #broadcast "bounty claimed: %{playerBounty::%victim's uuid%}%"
        #wait 1 tick
        #clear {playerBounty::%victim's uuid%}

    if event-damagecause is entity explosion:
        set {_uuid} to metadata value "playerWhoDetonated" of attacker
        #broadcast "<bold>Crystal kill detected - %{_uuid}%"
        #broadcast "UUID of playerWhoDetonated: %{_uuid}%"
        clear {killStreak::%victim's uuid%}		
        add 1 to {killStreak::%{_uuid}%}
        set {_playerWhoDetonated} to {_uuid} parsed as offline player
        give 5 sunflower named "<reset><yellow>&lCoin" to {_playerWhoDetonated}    
        give 1 amethyst shard named "<reset><purple><bold>Weekly Token - Week 1" to {_playerWhoDetonated}
        send "&aEnemy Down" to {_playerWhoDetonated}
        checkKS({_playerWhoDetonated})
        if {playerBounty::%victim's uuid%} is set:
            give {playerBounty::%victim's uuid%} to {_playerWhoDetonated}
            broadcast "%{_playerWhoDetonated}% claimed the bounty: %{playerBounty::%victim's uuid%}%"
            wait 1 tick
            clear {playerBounty::%victim's uuid%}
    else if event-damagecause is block explosion:
        set {_uuid} to {anchorkiller}
        #broadcast "<bold>Anchor kill detected - %{_uuid}%"
        #broadcast "UUID of playerWhoDetonated: %{_uuid}%"
        clear {killStreak::%victim's uuid%}		
        add 1 to {killStreak::%{_uuid}%}
        set {anchorkiller} to {_uuid} parsed as offline player
        give 5 sunflower named "<reset><yellow>&lCoin" to {anchorkiller}    
        give 1 amethyst shard named "<reset><purple><bold>Weekly Token - Week 1" to {anchorkiller}
        send "&aEnemy Down" to {anchorkiller}
        checkKS({anchorkiller})
        if {playerBounty::%victim's uuid%} is set:
            give {playerBounty::%victim's uuid%} to {anchorkiller}
            broadcast "%{anchorkiller}% claimed the bounty: %{playerBounty::%victim's uuid%}%"
            wait 1 tick
            clear {playerBounty::%victim's uuid%}
    else:
        set {_uuid} to attacker's uuid
        give 5 sunflower named "<reset><yellow>&lCoin" to attacker    
        give 1 amethyst shard named "<reset><purple><bold>Weekly Token - Week 1" to attacker
        #broadcast "UUID of playerWhoDetonated: %{_uuid}%"
        clear {killStreak::%victim's uuid%}		
        add 1 to {killStreak::%{_uuid}%}
        send "&aEnemy Down" to attacker
        checkKS(attacker)
        if {playerBounty::%victim's uuid%} is set:
            give {playerBounty::%victim's uuid%} to attacker
            broadcast "%attacker% claimed the bounty: %{playerBounty::%victim's uuid%}%"
            wait 1 tick
            clear {playerBounty::%victim's uuid%}



on damage of ender crystal:
    set metadata value "playerWhoDetonated" of victim to uuid of attacker
    #broadcast "Metadata value pWhoDetonated is the player %attacker% and the victim was a %victim%"
    
on rightclick on respawn anchor:
    set {anchorkiller} to player's uuid
    #set metadata value "playerWhoDetonated" of {anchorkiller} to player's uuid
    #broadcast "Anchorkiller: %{anchorkiller}%"
    #broadcast "anchorkiller: %{anchorkiller}%, pWhoDetonated: %metadata value "playerWhoDetonated" of {anchorkiller}%"
    #broadcast "Metadata value pWhoDetonated is %metadata value "playerWhoDetonated" of player% and the victim was a %player%"

#on projectile hit:
    #if victim is a explosive minecart:
        #set metadata value "playerWhoDetonated" of victim to uuid of attacker
        #broadcast "Metadata value pWhoDetonated is the player %attacker% and the victim was a %victim%"




command killstreak [<offlineplayer>]:
    trigger:
        arg-1 is not set:
            {killStreak::%player's uuid%} is set:
                send "Your current Kill Streak is %{killStreak::%player's uuid%}%"
            else:
                send "Your current Kill Streak is 0"
        else:
            {killStreak::%arg-1's uuid%} is set:
                send "%arg-1%'s current Kill Streak is %{killStreak::%arg-1's uuid%}%"
            else:
                send "%arg-1%'s current Kill Streak is 0"
				
command setkillstreak <number> [to] <player=%player%>:
    permission: skript.admin
    trigger:
        set {killStreak::%arg-2's uuid%} to arg-1
        send "Set KS to %{killStreak::%arg-2's uuid%}%"
        checkKS(arg-2)

command /test:
    permission: skript.admin
    trigger:
        set slot 0 of player's inventory to sunflower named "<reset><yellow>&lCoin"
        set slot 1 of player's inventory to paper named "<red><bold>Currently DISABLED until balancing is complete"
        set slot 2 of player's inventory to 2 paper named "<reset><red>&lKillstreak Voucher"
        set slot 3 of player's inventory to 1 amethyst shard named "<reset><purple><bold>Weekly Token - Week 1"


command testspecialkit <player=%player%>:
    permission: skript.admin
    trigger:
        set {specialkitlist::%arg-1's uuid%} to 1
        broadcast "<red><bold><italic>%{_p}% Has randomly recieved a DIVINE BLESSING: Swordsman of the Abyss"
        set slot 0 of arg-1's inventory to (netherite sword of sharpness 5 and sweeping edge 3 and fire aspect 2) named "<black><bold>Starless Night"
        set slot 1 of arg-1's inventory to 16 of ender pearl
        set slot 2 of arg-1's inventory to splash potion of strong strength
        set slot 3 of arg-1's inventory to splash potion of strong speed
        set slot 4 of arg-1's inventory to splash potion of strong strength
        set slot 5 of arg-1's inventory to splash potion of strong speed
        set slot 6 of arg-1's inventory to splash potion of strong strength
        set slot 7 of arg-1's inventory to splash potion of strong speed
        set slot 8 of arg-1's inventory to 64 of golden apple
        set slot 9 of arg-1's inventory to splash potion of strong turtle master
        set slot 10 of arg-1's inventory to splash potion of strong turtle master
        set arg-1's helmet to red silence netherite helmet of protection 3 and unbreaking 3 and curse of binding
        set arg-1's chestplate to red silence netherite chestplate of protection 3 and unbreaking 3 and curse of binding
        set arg-1's leggings to red silence netherite leggings of protection 3 and unbreaking 3 and curse of binding
        set arg-1's boots to red silence netherite boots of protection 3 and unbreaking 3 and curse of binding


command /enchantsk <enchantment type>:
    permission: skript.enchant
    trigger:
        enchant player's tool with arg-1
        message "<bold>Enchanted with %arg-1%"



command /rename [<text>]:
    permission: skript.rename
    description: Rename the item in your hand.
    trigger:
        if player's tool is not air:
            if arg-1 is set:
                set name of player's tool to colored arg-1
            else:
                message "&cpleas name >:("
        else:
            message "<bold> Can't name air."

command togglejunk:
    description: Toggle the picking up of junk like dirt and concrete powder
    trigger:
        if {pickupjunk::%player's uuid%} is not true:
            set {pickupjunk::%player's uuid%} to true
            send "You will now pick up 'junk' items."
        else:
            clear {pickupjunk::%player's uuid%}
            send "You will no longer pick up 'junk' items."

command toggleores:
    description: Toggle the picking up of iron, coal, and cobblestone (on by default)
    trigger:
        if {pickupores::%player's uuid%} is not true:
            set {pickupores::%player's uuid%} to true
            send "You will now pick up 'junk' ores."
        else:
            clear {pickupores::%player's uuid%}
            send "You will no longer pick up 'junk' ores."        

command /discord:
    trigger:
        send "&cJoin the discord! Huge Giveaways! &d&l&n<link:https://discord.gg/yffwheQ8>ClICK" to player

every 3 minutes:
    loop all players:
        send "&c<bold>Use <green><bold>/discord &c<bold>for huge giveaways and updates!" to loop-player

command /rekit:
    trigger:
        if {freerekit::%player's uuid%} is true:
            randomKit(player)
            clear {freerekit::%player's uuid%}
        else if player is holding 3 sunflowers named "<yellow><bold>Coin":
            set player's held item to air
            send "<bold>Kit rerolled!"
            randomKit(player)
        else:
            send "You need to hold 3 coins to reroll"
on shoot:
    shooter is a player
    name of shooter's held item is "<white><bold>AWP"
    set metadata value "custom" of event-projectile to "<white><bold>AWP"

on damage:
    "%damage cause%" is "projectile"
    metadata value "custom" of event-projectile is "<white><bold>AWP"
    cancel event
    kill event-projectile
    damage victim by 15 hearts
    apply blindness 4 to victim for 2 seconds
    apply slowness 3 to victim for 2 seconds
    apply glowing to victim for 5 seconds
    play sound "entity.player.levelup" to attacker

on damage:
    if "%damage cause%" is "projectile":
        if name of attacker's tool contains "<white><bold>AA-12":
            set maximum damage delay of victim to 0 seconds
            wait 3 tick
            set damage delay of victim to 0.5 seconds
        if name of attacker's tool contains "<white><bold>Remington 870":
            set maximum damage delay of victim to 0 seconds
            wait 3 tick
            set damage delay of victim to 0.5 seconds     

on explode:
    if event-entity is wither:
        cancel the event
        create an explosion of force 70 at event-location
    if event-entity is fireball:
        cancel the event
        create an explosion of force 5 at event-location
    if event-entity is explosive minecart:
        cancel the event
        create an explosion of force 10 at event-location
    if event-entity is tnt:
        cancel the event
        create an explosion of force 11 at event-location
    if event-entity is creeper:
        cancel the event
        create an explosion of force 15 at event-location


on teleport:
    set {_lastTeleportLocation} to location of player
    wait 2 ticks  
    
    if {_lastTeleportLocation} is not location of player:
        damage the player by 1


on projectile hit:
    if name of shooter's tool contains "<red><bold><italic>Boom<white><bold><italic>Bow":
        delete projectile
        wait 1 tick
        create explosion of force 2.5 at location
    if name of shooter's tool contains "<red><bold>RPG":
        delete projectile
        wait 1 tick
        create explosion of force 7 at location

on entity shoot bow:
    if name of shooter's tool contains "<white><bold>Remington 870":
        delete projectile
        wait 1 tick
        if player has 20 arrows:
            remove 20 arrows from player's inventory
            make the player shoot an arrow at speed 2
            make the player shoot an arrow at speed 2
            push last shot projectile right at speed 0.05
            make the player shoot an arrow at speed 2
            push last shot projectile left at speed 0.05
            make the player shoot an arrow at speed 2
            push last shot projectile upwards at speed 0.05
            make the player shoot an arrow at speed 2
            push last shot projectile downwards at speed 0.05
            make the player shoot an arrow at speed 2
            push last shot projectile downwards at speed 0.05
            push last shot projectile left at speed 0.05
            make the player shoot an arrow at speed 2
            push last shot projectile downwards at speed 0.05
            push last shot projectile right at speed 0.05
            make the player shoot an arrow at speed 2
            push last shot projectile upwards at speed 0.05
            push last shot projectile left at speed 0.05
            make the player shoot an arrow at speed 2
            push last shot projectile upwards at speed 0.05
            push last shot projectile right at speed 0.05
    
            make the player shoot an arrow at speed 2
            push last shot projectile right at speed 0.1
            make the player shoot an arrow at speed 2
            push last shot projectile left at speed 0.1
            make the player shoot an arrow at speed 2
            push last shot projectile upwards at speed 0.1
            make the player shoot an arrow at speed 2
            push last shot projectile downwards at speed 0.1
            make the player shoot an arrow at speed 2
            push last shot projectile downwards at speed 0.1
            push last shot projectile left at speed 0.1
            make the player shoot an arrow at speed 2
            push last shot projectile downwards at speed 0.1
            push last shot projectile right at speed 0.1
            make the player shoot an arrow at speed 2
            push last shot projectile upwards at speed 0.1
            push last shot projectile left at speed 0.1
            make the player shoot an arrow at speed 2
            push last shot projectile upwards at speed 0.1
            push last shot projectile right at speed 0.1
        else:
            send "You need at least 20 regular arrows" to player
    else if name of shooter's tool contains "<white><bold>AA-12":
        cancel event
        if player has 20 arrows:
            remove 20 arrows from player's inventory
            make the player shoot an arrow at speed 1
            make the player shoot an arrow at speed 1
            push last shot projectile right at speed 0.1
            make the player shoot an arrow at speed 1
            push last shot projectile left at speed 0.1
            make the player shoot an arrow at speed 1
            push last shot projectile upwards at speed 0.1
            make the player shoot an arrow at speed 1
            push last shot projectile downwards at speed 0.1
            make the player shoot an arrow at speed 1
            push last shot projectile downwards at speed 0.1
            push last shot projectile left at speed 0.1
            make the player shoot an arrow at speed 1
            push last shot projectile downwards at speed 0.1
            push last shot projectile right at speed 0.1
            make the player shoot an arrow at speed 1
            push last shot projectile upwards at speed 0.1
            push last shot projectile left at speed 0.1
            make the player shoot an arrow at speed 1
            push last shot projectile upwards at speed 0.1
            push last shot projectile right at speed 0.1
    
            make the player shoot an arrow at speed 1
            push last shot projectile right at speed 0.2
            make the player shoot an arrow at speed 1
            push last shot projectile left at speed 0.2
            make the player shoot an arrow at speed 1
            push last shot projectile upwards at speed 0.2
            make the player shoot an arrow at speed 1
            push last shot projectile downwards at speed 0.2
            make the player shoot an arrow at speed 1
            push last shot projectile downwards at speed 0.2
            push last shot projectile left at speed 0.2
            make the player shoot an arrow at speed 1
            push last shot projectile downwards at speed 0.2
            push last shot projectile right at speed 0.2
            make the player shoot an arrow at speed 1
            push last shot projectile upwards at speed 0.2
            push last shot projectile left at speed 0.2
            make the player shoot an arrow at speed 1
            push last shot projectile upwards at speed 0.2
            push last shot projectile right at speed 0.2
        else:
            send "You need at least 20 regular arrows" to player
    else if name of shooter's tool contains "<white><bold>AWP":
        cancel event
        make the player shoot an arrow at speed 6
    
    
command /eredeem:
    trigger:
        if name of player's held item contains "<purple><bold>Event Voucher - Week 1":
            set player's held item to air
            set {event1::%player's uuid%} to true
            send "<purple><bold><underline>Event voucher redeemed!"

        else:
            send "<red>Hold the event voucher in your hand!" to player
    	
    
on drop:
    if name of event-item contains "Permanent":
        delete event-dropped item
    
