command /norekit <player>:
    permission: op
    trigger:
        set {norekit} to arg-1's uuid
        broadcast "NO rekit successful"
        wait 5 second
        clear {norekit}
    

command /vip1:
    permission: skript.vip
    permission message: Hey! You need to pay to use this command ;)
    cooldown: 32 hours
    cooldown message: The cooldown for this command is 32 hours, sorry! :D
    trigger:
        clear player's inventory
        set player's helmet to emerald silence diamond helmet of protection 4 and unbreaking 3 and mending named "<green><bold>VIP HELMET"
        set player's boots to emerald silence diamond boots of protection 4 and unbreaking 3 and mending named "<green><bold>VIP BOOTS"
        set player's leggings to emerald silence diamond leggings of blast protection 4 and unbreaking 3 and mending named "<green><bold>VIP LEGGINGS"
        set player's chestplate to emerald silence diamond chestplate of protection 4 and unbreaking 3 and mending named "<green><bold>VIP CHESTPLATE"
        set slot 0 of player's inventory to diamond sword of sharpness 5 and knockback 1 and unbreaking 3 and mending named "<green><bold>VIP SWORD"
        set slot 1 of player's inventory to 16 of ender pearl
        set slot 2 of player's inventory to 64 of end crystal
        set slot 3 of player's inventory to 64 of obsidian
        set slot 4 of player's inventory to 64 of glowstone
        set slot 5 of player's inventory to 64 of respawn anchor
        set slot 6 of player's inventory to bow of power 5 and punch 2 and unbreaking 3 and mending
        set slot 7 of player's inventory to totem of undying of mending
        set slot 8 of player's inventory to 64 of golden apple
        set slot 9 of player's inventory to 16 of ender pearl
        set slot 18 of player's inventory to 16 of ender pearl
        set slot 27 of player's inventory to 16 of ender pearl
        set slot 28 of player's inventory to 64 of experience bottle
        set slot 10 of player's inventory to totem of undying of mending
        set slot 19 of player's inventory to totem of undying of mending
        set slot 14 of player's inventory to totem of undying of mending
        set slot 11 of player's inventory to totem of undying of mending
        set slot 12 of player's inventory to totem of undying of mending
        set slot 13 of player's inventory to totem of undying of mending
        set slot 20 of player's inventory to totem of undying of mending
        set slot 21 of player's inventory to totem of undying of mending
        set slot 22 of player's inventory to totem of undying of mending
        set slot 23 of player's inventory to totem of undying of mending
        set slot 29 of player's inventory to totem of undying of mending
        set slot 30 of player's inventory to totem of undying of mending
        set slot 31 of player's inventory to totem of undying of mending
        set slot 32 of player's inventory to totem of undying of mending
        set slot 15 of player's inventory to 64 of tipped arrow of long slow falling
        set slot 24 of player's inventory to shield of unbreaking 3 and mending
        set the off hand item of player to totem of undying of mending
command /vip2:
    permission: skript.vip
    permission message: Hey! You need to pay to use this command ;)
    cooldown: 58 hours
    cooldown message: The cooldown for this command is 58 hours, sorry! :D
    trigger:
        clear player's inventory
        set player's helmet to emerald silence netherite helmet of protection 4 and unbreaking 3 and mending named "<green><bold>VIP HELMET"
        set player's boots to emerald silence netherite boots of protection 4 and unbreaking 3 and mending named "<green><bold>VIP BOOTS"
        set player's leggings to emerald silence netherite leggings of blast protection 4 and unbreaking 3 and mending named "<green><bold>VIP LEGGINGS"
        set player's chestplate to emerald silence netherite chestplate of protection 4 and unbreaking 3 and mending named "<green><bold>VIP CHESTPLATE"
        set slot 0 of player's inventory to diamond sword of sharpness 5 and knockback 1 and unbreaking 3 and mending named "<green><bold>VIP SWORD"
        set slot 1 of player's inventory to 16 of ender pearl
        set slot 2 of player's inventory to 64 of end crystal
        set slot 3 of player's inventory to 64 of obsidian
        set slot 4 of player's inventory to 64 of glowstone
        set slot 5 of player's inventory to 64 of respawn anchor
        set slot 6 of player's inventory to bow of power 5 and punch 2 and unbreaking 3 and mending
        set slot 7 of player's inventory to totem of undying of mending
        set slot 8 of player's inventory to 64 of golden apple
        set slot 9 of player's inventory to 16 of ender pearl
        set slot 18 of player's inventory to 16 of ender pearl
        set slot 27 of player's inventory to 16 of ender pearl
        set slot 28 of player's inventory to 64 of experience bottle
        set slot 10 of player's inventory to totem of undying of mending
        set slot 19 of player's inventory to totem of undying of mending
        set slot 14 of player's inventory to totem of undying of mending
        set slot 11 of player's inventory to totem of undying of mending
        set slot 12 of player's inventory to totem of undying of mending
        set slot 13 of player's inventory to totem of undying of mending
        set slot 20 of player's inventory to totem of undying of mending
        set slot 21 of player's inventory to totem of undying of mending
        set slot 22 of player's inventory to totem of undying of mending
        set slot 23 of player's inventory to totem of undying of mending
        set slot 29 of player's inventory to totem of undying of mending
        set slot 30 of player's inventory to totem of undying of mending
        set slot 31 of player's inventory to totem of undying of mending
        set slot 32 of player's inventory to totem of undying of mending
        set slot 15 of player's inventory to 64 of tipped arrow of long slow falling
        set slot 24 of player's inventory to shield of unbreaking 3 and mending
        set the off hand item of player to totem of undying of mending
on damage:
    if victim is a dropped item:
        victim is not dropped moss block
        victim is not dropped cobblestone
        victim is not dropped totem of undying
        victim is not dropped coal
        victim is not dropped green concrete powder
        victim is not dropped dirt
        victim is not dropped glowstone dust
        victim is not dropped sand
        if damage cause is not lava:
            cancel event


command checkevent <player>:
    trigger:
        send "Event 1: %{event1::%arg-1's uuid%}%, Event 2: %{event2::%arg-1's uuid%}%, Event 3: %{event3::%arg-1's uuid%}%, Event 4: %{event4::%arg-1's uuid%}%, Extra heart: %{extraheart::%arg-1's uuid%}%" to player



command store1 <player>:
    permission: op
    trigger:
        give a paper named "<purple><bold>Event voucher - Week 1" to arg-1
        execute console command "broadcast %arg-1% has bought an Event voucher from the online store! Thank them for supporting the server :D"
command store2 <player>:
    permission: op
    trigger:
        give a paper named "<purple><bold>Event voucher - Week 2" to arg-1
        execute console command "broadcast %arg-1% has bought an Event voucher from the online store! Thank them for supporting the server :D"
command store3 <player>:
    permission: op
    trigger:
        give a paper named "<purple><bold>Event voucher - Week 3" to arg-1
        execute console command "broadcast %arg-1% has bought an Event voucher from the online store! Thank them for supporting the server :D"
command storeheart <player>:
    permission: op
    trigger:
        give a nether star named "<purple><bold>Extra Heart" to arg-1
        execute console command "broadcast %arg-1% has bought an Event voucher from the online store! Thank them for supporting the server :D"

command /store:
    trigger:
        send "<green>Buy ranks and in-game currency here! &d&l&n<link:https://cdetonations.tebex.io/><Click here!>" to player



on first join:
    set {freerekit::%player's uuid%} to true
    set {firstjoin} to player
    set {firstjointimer} to 0
    while {firstjointimer} is smaller than 30:
        wait 1 second
        add 1 to {firstjointimer}
        if {firstjointimer} is 30:
            clear {firstjointimer}
            clear {playerwelcomecooldown::*}
on chat:
    if message contains "%{firstjoin}%":
        if {firstjointimer} is smaller than 30:
            if {playerwelcomecooldown::%player's uuid%} is not set:
                give player 16 sunflowers named "<reset><yellow><bold>Coin"
                send "&dYou recieved 16 coins for welcoming a new player! :D"
                set {playerwelcomecooldown::%player's uuid%} to true





on place of tnt:
    set event-block to air
    spawn primed tnt at event-location










on respawn:
    if respawn reason = death respawn:
        wait 6 seconds
        {norekit} is not player's uuid
        randomKit(player)
        if {event1::%player's uuid%} is set:
            give player (amethyst silence netherite boots of protection 3 and unbreaking 3 and mending and curse of vanishing) named "<dark gray><bold>Permanent Boots"
        if {event2::%player's uuid%} is set:
            give player (amethyst silence netherite chestplate of protection 3 and unbreaking 3 and mending and curse of vanishing) named "<dark gray><bold>Permanent Chestplate"
        if {event3::%player's uuid%} is set:
            give player (netherite sword of knockback 1 and sweeping edge 3 and curse of vanishing named "<dark gray><bold>[Permanent] <red><bold>Vampiric Blade")
            set {sharpness::%player's uuid%} to 0
        if {event4::%player's uuid%} is set:
            give player blaze rod of knockback 5 and curse of vanishing named "<dark grey><bold>[Permanent] <purple><bold>Necromantic Staff"


function randomKit(p: player):
    set {_Helmet} to random integer between 1 and 7
    if {_Helmet} is 1:
        set {_p}'s helmet to iron helmet of protection 1 and unbreaking 1 and blast protection 2
    else if {_Helmet} is 2:
        set {_p}'s helmet to iron helmet of protection 2 and unbreaking 1 and blast protection 3
    else if {_Helmet} is 3:
        set {_p}'s helmet to diamond helmet of protection 1
    else if {_Helmet} is 4:
        set {_p}'s helmet to diamond helmet of protection 2
    else if {_Helmet} is 5:
        set {_p}'s helmet to diamond helmet of protection 2 and blast protection 3
    else if {_Helmet} is 6:
        set {_p}'s helmet to gold helmet of protection 4 and unbreaking 1
    else if {_Helmet} is 7:
        set {_p}'s helmet to chainmail helmet of protection 3 and unbreaking 1

    set {_Chestplate} to random integer between 1 and 7
    if {_Chestplate} is 1:
        set {_p}'s chestplate to iron chestplate of protection 1 and unbreaking 1 and blast protection 2
    else if {_Chestplate} is 2:
        set {_p}'s chestplate to iron chestplate of protection 2 and unbreaking 1 and blast protection 3
    else if {_Chestplate} is 3:
        set {_p}'s chestplate to diamond chestplate of protection 1
    else if {_Chestplate} is 4:
        set {_p}'s chestplate to diamond chestplate of protection 2
    else if {_Chestplate} is 5:
        set {_p}'s chestplate to diamond chestplate of protection 2 and blast protection 3
    else if {_Chestplate} is 6:
        set {_p}'s chestplate to gold chestplate of protection 4 and unbreaking 1
    else if {_Chestplate} is 7:
        set {_p}'s chestplate to chainmail chestplate of protection 3 and unbreaking 1

    
    set {_Leggings} to random integer between 1 and 7
    if {_Leggings} is 1:
        set {_p}'s leggings to iron leggings of protection 1 and unbreaking 1 and blast protection 2
    else if {_Leggings} is 2:
        set {_p}'s leggings to iron leggings of protection 2 and unbreaking 1 and blast protection 3
    else if {_Leggings} is 3:
        set {_p}'s leggings to diamond leggings of protection 1
    else if {_Leggings} is 4:
        set {_p}'s leggings to diamond leggings of protection 2
    else if {_Leggings} is 5:
        set {_p}'s leggings to diamond leggings of protection 2 and blast protection 3
    else if {_Leggings} is 6:
        set {_p}'s leggings to gold leggings of protection 4 and unbreaking 1
    else if {_Leggings} is 7:
        set {_p}'s leggings to chainmail leggings of protection 3 and unbreaking 1

    set {_Boots} to random integer between 1 and 7
    if {_Boots} is 1:
        set {_p}'s boots to iron boots of protection 1 and unbreaking 1 and blast protection 2
    else if {_Boots} is 2:
        set {_p}'s boots to iron boots of protection 2 and unbreaking 1 and blast protection 3
    else if {_Boots} is 3:
        set {_p}'s boots to diamond boots of protection 1
    else if {_Boots} is 4:
        set {_p}'s boots to diamond boots of protection 2
    else if {_Boots} is 5:
        set {_p}'s boots to diamond boots of protection 2 and blast protection 3
    else if {_Boots} is 6:
        set {_p}'s boots to gold boots of protection 4 and unbreaking 1
    else if {_Boots} is 7:
        set {_p}'s boots to chainmail boots of protection 3 and unbreaking 1
    
    set {_Sword} to random integer between 1 and 4 
    if {_Sword} is 1:
        set slot 0 of {_p}'s inventory to iron sword of sharpness 1
    else if {_Sword} is 2:
        set slot 0 of {_p}'s inventory to diamond sword of sharpness 1
    else if {_Sword} is 3:
        set slot 0 of {_p}'s inventory to diamond sword of sharpness 2
    else if {_Sword} is 4:
        set slot 0 of {_p}'s inventory to netherite sword of sharpness 1
    else if {_Sword} is 5:
        set slot 0 of {_p}'s inventory to netherite sword of sharpness 1 and fire aspect 1
    else if {_Sword} is 6:
        set slot 0 of {_p}'s inventory to netherite sword of sharpness 2


    set {_Food} to random integer between 1 and 3
    if {_Food} is 1:
        set slot 8 of {_p}'s inventory to 8 of golden carrot
    else if {_Food} is 2:
        set slot 8 of {_p}'s inventory to 12 of steak
    else if {_Food} is 3:
        set slot 8 of {_p}'s inventory to 32 of bread
		
		
    set {_Weapon} to random integer between 1 and 7
    if {_Weapon} is 1:
        set slot 4 of {_p}'s inventory to lava bucket
        set slot 7 of {_p}'s inventory to water bucket
    else if {_Weapon} is 2:
        set slot 4 of {_p}'s inventory to water bucket
        set slot 7 of {_p}'s inventory to water bucket
    else if {_Weapon} is 3:
        set slot 4 of {_p}'s inventory to lava bucket
    else if {_Weapon} is 4:
        set slot 5 of {_p}'s inventory to 16 of cobweb
        set slot 4 of {_p}'s inventory to lava bucket
        set slot 7 of {_p}'s inventory to water bucket
    else if {_Weapon} is 5:
        set slot 5 of {_p}'s inventory to 16 of cobweb
    else if {_Weapon} is 6:
        set slot 5 of {_p}'s inventory to 4 of end crystal   
        set slot 3 of {_p}'s inventory to 8 of Obsidian
    else if {_Weapon} is 7:
        set slot 4 of {_p}'s inventory to 6 of glowstone
        set slot 5 of {_p}'s inventory to 2 of respawn anchor
    chance of 10%:	
        set the off hand item of {_p} to totem of undying
    set {_axe} to random integer between 1 and 10
    if {_axe} is 3:
        set slot 2 of {_p}'s inventory to iron axe of sharpness 1
    if {_axe} is 4:
        set slot 2 of {_p}'s inventory to iron axe of sharpness 3
    if {_axe} is 5:
        set slot 2 of {_p}'s inventory to diamond axe of sharpness 1
    if {_axe} is 6:
        set slot 2 of {_p}'s inventory to diamond axe of sharpness 2
    if {_axe} is 7:
        set slot 2 of {_p}'s inventory to netherite axe of sharpness 1
    
    chance of 5%:
        chance of 50%:
            set {_p}'s boots to netherite boots of protection 1 and blast protection 3
        chance of 50%:
            set {_p}'s boots to netherite boots of protection 1
    chance of 5%:
        chance of 50%:
            set {_p}'s leggings to netherite leggings of protection 1 and blast protection 3
        chance of 50%:
            set {_p}'s leggings to netherite leggings of protection 1
    chance of 5%:
        chance of 50%:
            set {_p}'s chestplate to netherite chestplate of protection 1 and blast protection 3
        chance of 50%:
            set {_p}'s chestplate to netherite chestplate of protection 1
    chance of 5%:
        chance of 50%:
            set {_p}'s helmet to netherite helmet of protection 1 and blast protection 3
        chance of 50%:
            set {_p}'s helmet to netherite helmet of protection 1



    set {_Pickaxe} to random integer between 1 and 8
    if {_Pickaxe} is 1:
        give iron Pickaxe of efficiency 1 and fortune 3 to {_p}
    else if {_Pickaxe} is 2:
        give diamond Pickaxe of efficiency 3 to {_p}
    else if {_Pickaxe} is 3:
        give diamond Pickaxe of efficiency 2 to {_p}
    else if {_Pickaxe} is 4:
        give diamond Pickaxe of efficiency 1 to {_p}
    else if {_Pickaxe} is 5:
        give netherite Pickaxe of efficiency 2 to {_p}
    else if {_Pickaxe} is 6:
        give netherite Pickaxe of efficiency 1 to {_p}

    set {_Bow} to random integer between 1 and 5 
    if {_Bow} is 1:
        give bow of power 1 to {_p}
    else if {_Bow} is 2:
        give bow of power 2 to {_p}
    else if {_Bow} is 3:
        give bow of punch 2 to {_p}
    else if {_Bow} is 4:
        give crossbow of piercing 2 to {_p}
    else if {_Bow} is 5:
        give crossbow of quick charge 2 to {_p}
    set slot 17 of {_p}'s inventory to 24 arrows

    set {_Shield} to random integer between 1 and 3
    if {_Shield} is 1:
        set {_item} to shield of unbreaking 3
        set durability of {_item} to 100
        give {_item} to {_p}
    if {_Shield} is 2:
        set {_item} to shield
        give {_item} to {_p}
    if {_Shield} is 3:
        set {_item} to shield
        set durability of {_item} to 200
        give {_item} to {_p}

    set {_block} to random integer between 1 and 2
    if {_block} is 1:
        give 32 of cobblestone to {_p}
    else if {_block} is 2:
        give 32 of oak planks to {_p}


    chance of 10%:
        give 16 tnt to {_p}
    chance of 10%:
        give 8 tnt to {_p}
    chance of 10%:
        give fishing rod named "<white><bold>Grappling Hook" to {_p}
    chance of 10%:
        give 2 feather named "&b&lSpeed" to {_p}
    chance of 10%:
        give 2 acacia button named "&c&lEject Button" to {_p}


    set {_specialkit} to random integer between 1 and 150
    if {_specialkit} is 100:
        set {specialkitlist::%{_p}'s uuid%} to 1
        broadcast "<red><bold><italic>%{_p}% Has randomly recieved a DIVINE BLESSING: Fallen Armsman"
        set slot 0 of {_p}'s inventory to bow of multishot 5 and curse of vanishing named "<white><bold>AA-12"
        set the off hand item of {_p} to crossbow of quick charge 5 named "<grey><bold>M4A1"
        set slot 2 of {_p}'s inventory to 64 of tipped arrow of harming 
        set slot 3 of {_p}'s inventory to 64 of tipped arrow of harming 
        set {_p}'s helmet to chainmail helmet of blast protection 5 and protection 4 and curse of vanishing and curse of binding
        set {_p}'s chestplate to chainmail chestplate of blast protection 5 and protection 4 and curse of vanishing and curse of binding
        set {_p}'s leggings to chainmail leggings of blast protection 5 and protection 4 and curse of vanishing and curse of binding
        set {_p}'s boots to chainmail boots of blast protection 5 and protection 4 and curse of vanishing and curse of binding
        give or drop 1280 arrows of curse of vanishing to {_p}

    if {_specialkit} is 101:
        set {specialkitlist::%{_p}'s uuid%} to 1
        broadcast "<red><bold><italic>%{_p}% Has randomly recieved a DIVINE BLESSING: Swordsman of the Abyss"
        set slot 0 of {_p}'s inventory to (netherite sword of sharpness 2 and sweeping edge 3 and fire aspect 1) named "<grey><bold>Starless Night"
        set slot 1 of {_p}'s inventory to 16 of ender pearl
        set slot 2 of {_p}'s inventory to splash potion of strong strength
        set slot 3 of {_p}'s inventory to splash potion of strong speed
        set slot 4 of {_p}'s inventory to splash potion of strong strength
        set slot 5 of {_p}'s inventory to splash potion of strong speed
        set slot 6 of {_p}'s inventory to splash potion of strong strength
        set slot 7 of {_p}'s inventory to splash potion of strong speed
        set slot 8 of {_p}'s inventory to 12 of golden apple
        set slot 9 of {_p}'s inventory to splash potion of strong turtle master
        set slot 10 of {_p}'s inventory to splash potion of strong turtle master
        set slot 11 of {_p}'s inventory to splash potion of strong turtle master
        set slot 12 of {_p}'s inventory to splash potion of strong turtle master
        set slot 13 of {_p}'s inventory to splash potion of strong turtle master
        set slot 14 of {_p}'s inventory to splash potion of strong turtle master
        set slot 15 of {_p}'s inventory to splash potion of strong turtle master
        set {_p}'s helmet to red silence netherite helmet of protection 2 and unbreaking 3 and curse of binding
        set {_p}'s chestplate to red silence netherite chestplate of protection 2 and unbreaking 3 and curse of binding
        set {_p}'s leggings to red silence netherite leggings of protection 2 and blast protection 3 and unbreaking 3 and curse of binding
        set {_p}'s boots to red silence netherite boots of protection 2 and unbreaking 3 and curse of binding
on pick up:
    if event-item is end crystal:
        if {specialkitlist::%player's uuid%} is 1:
            cancel event
    if event-item is respawn anchor:
        if {specialkitlist::%player's uuid%} is 1:
            cancel event
    if event-item is green concrete powder:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is moss block:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is sandstone:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is smooth sandstone:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is dirt:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is end stone:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is sand:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is glowstone dust:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is tuff:
        if {pickupjunk::%player's uuid%} is not true:
            cancel event
    if event-item is raw iron:
        if {pickupores::%player's uuid%} is not true:
            cancel event
    if event-item is coal:
        if {pickupores::%player's uuid%} is not true:
            cancel event
    if event-item is cobblestone:
        if {pickupores::%player's uuid%} is not true:
            cancel event
    if event-item is cobbled deepslate:
        if {pickupores::%player's uuid%} is not true:
            cancel event

on right click:
    if name of player's held item contains "&b&lSpeed":
        difference between now and {speedcooldown::%player's uuid%} is not less than 15 seconds
        set {speedcooldown::%player's uuid%} to now
        remove 1 feather named "&b&lSpeed" from player's inventory
        apply speed of tier 7 to the player for 5 seconds
        set the cooldown of held item for player to 15 seconds
on place:
    If name of player's tool is "&c&lEject Button":
        cancel event
        remove 1 acacia button named "&c&lEject Button" from player's inventory
        loop all players in radius 10 of event-block:
            apply resistance of tier 5 to loop-player for 1 second
        create a safe explosion of force 10 at event-block
command /afk <player>:
    permission: op
    trigger:
        give 1 salmon named "&b&lAFK Token" to arg-1

on anvil damage:
    cancel event
        
